### ISSUE TITLE
Cookie sync issue in WebKitSyncCookieManager

### ISSUE THREAD

**Issue by hbj508** [gotev/android-cookie-store#12]
If maxAge is not set cookie is set as expired 
![image](https://user-images.githubusercontent.com/5156018/110011388-64a9d800-7d45-11eb-938a-fedeb966d0b4.png)

**Comment by gotev** [comment]
Thank you for the issue report. I would appreciate your review on https://github.com/gotev/android-cookie-store/pull/13 😉

**Comment by gotev** [comment]
Thank you for the review! Released `1.3.2` with the fix 😉
