### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException net.gotev.cookiestore.SharedPreferencesCookieStore.add

### ISSUE THREAD

**Issue by hbj508** [gotev/android-cookie-store#14]
java.util.ArrayList$Itr.next (ArrayList.java:860)
com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write (CollectionTypeAdapterFactory.java:96)
com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write (CollectionTypeAdapterFactory.java:61)
com.google.gson.Gson.toJson (Gson.java:704)
com.google.gson.Gson.toJson (Gson.java:683)
com.google.gson.Gson.toJson (Gson.java:638)
com.google.gson.Gson.toJson (Gson.java:618)
net.gotev.cookiestore.SharedPreferencesCookieStore.add (SharedPreferencesCookieStore.java:54)
java.net.CookieManager.put (CookieManager.java:360)

**Comment by gotev** [comment]
How can this be replicated?

**Comment by hbj508** [comment]
cannot replicate this. many users are getting this issue

**Comment by gotev** [comment]
This is linked to #4 Increased locking mechanisms and released `1.3.3` with the modification.

**Comment by hbj508** [comment]
we still this issue . should we  make a defensive copy as suggested by JakeWarthon here https://github.com/google/gson/issues/1159#issuecomment-330535301

**Comment by gotev** [comment]
You can now update to `1.3.5`
