### ISSUE TITLE
Cookie not storing across app reboots

### ISSUE THREAD

**Issue by CompuGeniusCode** [gotev/android-cookie-store#16]
I'm using OkHttp, and it saves cookies received while the app is still running, but once I close the app and restart, it no longer has the cookie. 
```kotlin
// Example extension function to demonstrate how to create both cookie stores
    private fun createCookieStore(name: String, persistent: Boolean) = if (persistent) {
        context?.let { SharedPreferencesCookieStore(it, name) }
    } else {
        InMemoryCookieStore(name)
    }


    private val cookieManager = CookieManager(
        createCookieStore(name = "myCookies", persistent = true),
        CookiePolicy.ACCEPT_ALL
    )

    private val client = OkHttpClient.Builder()
        .cookieJar(JavaNetCookieJar(cookieManager))
        .build()
```
This is how I have the code implemented.

**Comment by gotev** [comment]
Check your cookies expiration date

**Comment by CompuGeniusCode** [comment]
I don't think I use expiration dates, but will check

**Comment by CompuGeniusCode** [comment]
I set the `max_age` property to a week, yet it still doesn't save. I verified that the cookie's `max_age` is being set properly.

**Comment by gotev** [comment]
You should also define the `expires` attribute. `Max-Age` has to be written with `-` and not `_`. Check also the demo app which is a complete working example, that calls this page to set the cookie. It works after reboots.

```
curl https://www.gotev.net/cookiedemo/login.php -d '{"username":"userdemo"}' -D -
HTTP/2 201
server: nginx/1.10.3
date: Tue, 23 Mar 2021 18:44:16 GMT
content-type: text/html; charset=UTF-8
content-length: 0
set-cookie: LOGIN=userdemo; expires=Tue, 23-Mar-2021 18:46:16 GMT; Max-Age=120
```

**Comment by CompuGeniusCode** [comment]
I will try adding `expires`. I only spelled `max_age` as such because that's the parameter for `aiohttp`, but it does add it with a `-`.

**Comment by CompuGeniusCode** [comment]
`Set-Cookie: session=0cd0febe-266b-4239-aef1-241ed9aec440; expires=Tue, 30 Mar 2021 19:01:31 GMT; Max-Age=604800; Path=/` I get this response, yet for some reason, the app is still not saving between reboots.

**Comment by gotev** [comment]
Only thing I could notice is that your `expires` date lacks `-`
```
expires=Tue, 30 Mar 2021 19:01:31 GMT
```
mine:
```
expires=Tue, 23-Mar-2021 18:46:16 GMT
```
On my demo server I used php and that's the standard output I get from the setcookie function: https://www.php.net/manual/en/function.setcookie.php

**Comment by CompuGeniusCode** [comment]
According to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date), they don't need hyphens, but I will add just in case. Would sending the project over help in any way? (it's very small, so it's not hard to look through)

**Comment by CompuGeniusCode** [comment]
Adding hyphens did not help. It would help tremendously if you could take the time to check through my project a bit.

**Comment by gotev** [comment]
The demo app now has extensive debugging capabilities:
- you can see which cookies you get from your HTTP requests (just tap on the notification after you press Login)
- you can see which cookies are sent to which URLs by web view in LogCat (filter for COOKIE)

Using my own demo server and demo app everything works. The library is used in production on several apps without this kind of issue. What I suggest you to do is to fork the library, open the demo app, see the current implementation and replicate your behavior there. I don't have evidence the bug is in the library up to this point.

**Comment by CompuGeniusCode** [comment]
Is a WebView required for the cookies to be saved? Because that's pretty much the biggest difference I see. I will start removing stuff slowly just to see if I can narrow down what the problem is though.

**Comment by CompuGeniusCode** [comment]
Ok, I have figured it out. My `createCookieStore` function:
```kotlin
private fun createCookieStore(name: String, persistent: Boolean) = if (persistent) {
    context?.let { SharedPreferencesCookieStore(it, name) }
} else {
    InMemoryCookieStore(name)
}
```
was being run in a `Fragment`, therefore having no `context`, therefore not calling `SharedPreferencesCookieStore`. I have moved that code to an `Application`:
```kotlin
private fun createCookieStore(name: String, persistent: Boolean) = if (persistent) {
    SharedPreferencesCookieStore(this, name)
} else {
    InMemoryCookieStore(name)
}
```
and it works. Thanks for your help!

**Comment by gotev** [comment]
Great! 

> Is a WebView required for the cookies to be saved?

No, that's only an example. Added also an API call to demostrate pure API cookie injection. In the network inspector you can see both cookies from the server and those sent to it.
