### ISSUE TITLE
android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview

### ISSUE THREAD

**Issue by hbj508** [gotev/android-cookie-store#17]
Caused by android.util.AndroidRuntimeException
android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
android.webkit.WebViewFactory.getFactoryClass (WebViewFactory.java:195)
android.webkit.CookieManager.getInstance (CookieManager.java:42)
net.gotev.cookiestore.WebKitSyncCookieManager$webKitCookieManager$2.invoke (WebKitSyncCookieManager.java:14)
net.gotev.cookiestore.WebKitSyncCookieManager$webKitCookieManager$2.invoke (WebKitSyncCookieManager.java:8)
kotlin.SynchronizedLazyImpl.getValue (SynchronizedLazyImpl.java:74)
net.gotev.cookiestore.WebKitSyncCookieManager.getWebKitCookieManager (WebKitSyncCookieManager.java)

**Comment by gotev** [comment]
on which android version and with which library version?

**Comment by gotev** [comment]
It's an Android platform bug marked as wontfix: https://bugs.chromium.org/p/chromium/issues/detail?id=506369

Recently, Google failed an Android System WebView update, which generated (and still does) a lot of crashes: https://www.theverge.com/2021/3/22/22345696/google-android-apps-crashing-fix-system-webview

**Comment by hbj508** [comment]
this issue is even seen on Android 10/11. i think adding try catch would help as users not having webview only cookies wont be synced. currently it crashes for those users

**Comment by gotev** [comment]
I agree, at least it won't crash. Opened a PR #18 😉 a review is greatly appreciated

**Comment by gotev** [comment]
Fixed by `1.3.4`
