### ISSUE TITLE
Proguard Support

### ISSUE THREAD

**Issue by jimmymorales** [gotev/android-cookie-store#2]
When enabling Proguard, `SharedPreferencesCookieStore` is not parsing correctly saved preferences probably due to `HttpCookie` class being minified/obfuscate by Proguard.

I manage to fix it by adding `-keep class java.net.HttpCookie { <fields>; }` in my `proguard-rules.pro` file.

It will be great if this can be handle by the library or adding a Proguard section in the README.

**Comment by gotev** [comment]
@jimmymorales definitely I will add ProGuard section in the README as a starting point. Is it the only error you got? Best thing will be to add ProGuard rules directly in the Cookie Store Example App release configuration, so this could be easily tested with a test suite later on. Are you willing to do it with a PR? Thank you!

**Comment by jimmymorales** [comment]
Thanks for the reply.
Sure, I can help with the PR.

**Comment by gotev** [comment]
@jimmymorales thank you for this implementation 😃  

Starting from `1.2.2` which was just published, ProGuard rules are implemented and more can be added onwards
