### ISSUE TITLE
Crashes happen #java.lang.NullPointer Exception

### ISSUE THREAD

**Issue by gmg-avid** [gotev/android-cookie-store#24]
<img width="1155" alt="Screenshot 2021-10-08 at 10 09 56 AM" src="https://user-images.githubusercontent.com/77985558/136499485-672b062e-220e-44b2-abdf-2895dd7a8022.png">

**Comment by gotev** [comment]
Thank you for the report! Fixed in https://github.com/gotev/android-cookie-store/releases/tag/1.4.0
