### ISSUE TITLE
Possible to use EncryptedSharedPreferences?

### ISSUE THREAD

**Issue by lttlang** [gotev/android-cookie-store#33]
What are your thoughts on modifying/adding an implementation where the `SharedPreferencesCookieStore` uses an `EncryptedSharedPreference`? I tried to extend `InMemoryCookieStore` with my own implementation with `EncryptedSharedPreference`, but was unable to reference the underlying map of URIs and cookies (`uriIndex`)

**Comment by gotev** [comment]
You can create your encrypted preferences class extending InMemoryCookieStore, taking https://github.com/gotev/android-cookie-store/blob/master/cookie-store/src/main/java/net/gotev/cookiestore/SharedPreferencesCookieStore.kt as an example. You shouldn't need to reference any internal properties, as your source of truth is your encrypted shared preference file.

**Comment by lttlang** [comment]
Ah I think I was mistaken. I assumed I needed to reference `uriIndex` directly, but I could just call the add/remove functions in InMemoryCookieStore in order to keep the 2 cookie stores in sync. Thanks for replying!
