### ISSUE TITLE
Bring cookies from android.webkit.CookieManager to OkHttp's requests

### ISSUE THREAD

**Issue by hungntv** [gotev/android-cookie-store#36]
First, thanks for your work. I love this repo.

I have a question:
Can we inject cookies from `android.webkit.CookieManager` (cookies was made by Android Webview) into every request of OkHttp?

Thanks

**Comment by gotev** [comment]
The library is not designed for this, mainly because it will be a major security issue to have cookies injected by a webview synced and sent over in each of your requests. The lib aims at allowing you to share existing cookies obtained from API calls to the web view, not the other way around.
